# Generated by Django 2.2.5 on 2019-09-26 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('images', models.ImageField(default='', upload_to='')),
                ('desc', models.CharField(default='', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BlogSpots',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(error_messages={'required': 'Please enter your name'}, max_length=300)),
                ('heading1', models.CharField(default='', max_length=250)),
                ('heading2', models.CharField(default='', max_length=250)),
                ('content1', models.TextField(default='', max_length=25500)),
                ('content2', models.TextField(default='', max_length=25500)),
                ('keywords', models.CharField(max_length=1000)),
                ('links', models.CharField(blank=True, default='', max_length=500)),
                ('catagory', models.CharField(default='', max_length=30)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('images', models.FileField(upload_to='')),
                ('thumbnils', models.FileField(upload_to='')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
    ]
